### PR TITLE
Add support for Cypher code blocks in Markdown

### PR DESCRIPTION
**Pull request by mattorp**
Based on this implementation: https://stackoverflow.com/a/76239666/3876654

### CODE REVIEW

**Comment by mattorp** [comment]
I'd also like to add automatic selection in code blocks for running cypher queries when inside a code block with no selection. Any suggestions for where/how to add this implementation?

**Comment by mattorp** [comment]
Added an initial implementation for the auto-select within code-blocks based on cursors position. Haven't tested extensively though.

**Comment by adam-cowley** [comment]
Thanks for this.   What is still missing in your eyes?  What is the best way for me to test this?

**Comment by mattorp** [comment]
I created a new PR, with squashed commits and handling of multiple blocks/cursors. This one got a bit messy.

I've tested it quite thoroughly, but haven't added tests to the code. Would you prefer that? Otherwise I believe everything should be in place now.

**Pull request closed without merging**
